/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ARCapture {
  'id' : string,
  'title' : string,
  'imageData' : string,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
  'sceneId' : string,
}
export interface AncestryInsights {
  'foods' : Array<string>,
  'migrationStory' : string,
  'festivals' : Array<string>,
  'familyTreeNodes' : Array<FamilyTreeNode>,
  'traditionalOccupations' : Array<string>,
  'forgottenCustoms' : Array<string>,
}
export interface Course {
  'id' : ItemId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isLive' : boolean,
  'instructorId' : UserId,
  'imageUrl' : string,
  'durationMinutes' : bigint,
  'category' : CourseCategory,
  'maxParticipants' : bigint,
  'price' : bigint,
  'instructorName' : string,
  'scheduledAt' : [] | [Timestamp],
}
export type CourseCategory = { 'music' : null } |
  { 'yoga' : null } |
  { 'cooking' : null } |
  { 'pottery' : null } |
  { 'martialArts' : null } |
  { 'regionalArts' : null } |
  { 'dance' : null } |
  { 'weaving' : null } |
  { 'calligraphy' : null };
export interface DailyLesson {
  'id' : ItemId,
  'title' : string,
  'content' : string,
  'lessonNumber' : bigint,
  'createdAt' : Timestamp,
  'audioUrl' : string,
  'language' : string,
  'practiceWords' : Array<string>,
}
export interface Enrollment {
  'id' : ItemId,
  'completedAt' : [] | [Timestamp],
  'userId' : UserId,
  'enrolledAt' : Timestamp,
  'certified' : boolean,
  'courseId' : ItemId,
  'progressPct' : bigint,
}
export interface FamilyTimeline {
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'itemIds' : Array<ItemId>,
}
export interface FamilyTreeNode {
  'era' : string,
  'region' : string,
  'relation' : string,
  'name' : string,
}
export interface Festival {
  'id' : ItemId,
  'region' : string,
  'celebrationGuide' : string,
  'recipes' : Array<string>,
  'meaning' : string,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'languages' : Array<string>,
  'description' : string,
  'imageUrl' : string,
  'clothingSuggestions' : Array<string>,
  'rituals' : Array<string>,
}
export interface FestivalPlan {
  'id' : ItemId,
  'reminderAt' : [] | [Timestamp],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'festivalId' : ItemId,
  'notes' : string,
  'familyParticipants' : Array<string>,
}
export interface HeritageProfile {
  'region' : string,
  'foods' : Array<string>,
  'familyBackground' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'migrationStory' : string,
  'surname' : string,
  'festivals' : Array<string>,
  'ancestryInsights' : string,
  'language' : string,
  'updatedAt' : Timestamp,
  'grandparentsOrigin' : string,
  'traditionalOccupations' : Array<string>,
  'forgottenCustoms' : Array<string>,
}
export type ItemId = bigint;
export interface LanguageProgress {
  'wordsLearned' : bigint,
  'startedAt' : Timestamp,
  'userId' : UserId,
  'lastActiveAt' : Timestamp,
  'totalLessonsCompleted' : bigint,
  'conversationLevel' : string,
  'streakDays' : bigint,
  'currentLesson' : bigint,
  'scriptsLearned' : Array<string>,
  'languageChosen' : string,
  'pronunciationScore' : bigint,
}
export interface Listing {
  'id' : ItemId,
  'region' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'stock' : bigint,
  'category' : ProductCategory,
  'sellerId' : UserId,
  'price' : bigint,
}
export type MediaType = { 'voiceNote' : null } |
  { 'video' : null } |
  { 'letter' : null } |
  { 'handwrittenNote' : null } |
  { 'photo' : null };
export interface MentorBooking {
  'id' : ItemId,
  'status' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'instructorId' : UserId,
  'durationMinutes' : bigint,
  'notes' : string,
  'scheduledAt' : Timestamp,
}
export interface Order {
  'id' : ItemId,
  'status' : OrderStatus,
  'listingId' : ItemId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'quantity' : bigint,
  'shippingAddress' : string,
  'sellerId' : UserId,
  'stripeSessionId' : string,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export type ProductCategory = { 'art' : null } |
  { 'artisanProduct' : null } |
  { 'book' : null } |
  { 'instrument' : null } |
  { 'craft' : null } |
  { 'jewelry' : null } |
  { 'textile' : null };
export interface SellerStats {
  'totalOrders' : bigint,
  'totalListings' : bigint,
  'sellerId' : UserId,
  'rating' : bigint,
  'totalRevenue' : bigint,
}
export interface StoryItem {
  'id' : ItemId,
  'title' : string,
  'yearApprox' : [] | [bigint],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'peopleTagged' : Array<string>,
  'updatedAt' : Timestamp,
  'fileId' : string,
  'narration' : string,
  'mediaType' : MediaType,
}
export type Timestamp = bigint;
export type TraditionCategory = { 'clothing' : null } |
  { 'custom' : null } |
  { 'ritual' : null } |
  { 'spiritualPractice' : null } |
  { 'folkSong' : null } |
  { 'dance' : null } |
  { 'celebration' : null } |
  { 'recipe' : null };
export interface TraditionItem {
  'id' : ItemId,
  'region' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'languages' : Array<string>,
  'description' : string,
  'steps' : Array<string>,
  'imageUrl' : string,
  'category' : TraditionCategory,
}
export interface UserActivitySummary {
  'storiesSaved' : bigint,
  'arCaptures' : bigint,
  'languageLessons' : bigint,
  'coursesEnrolled' : bigint,
  'ordersPlaced' : bigint,
  'festivalPlans' : bigint,
  'heritageScans' : bigint,
}
export type UserId = Principal;
export interface UserProfile {
  'lastLoginAt' : Timestamp,
  'createdAt' : Timestamp,
  'fullName' : string,
  'languageInterests' : Array<string>,
  'heritageRegion' : string,
  'email' : string,
  'principalId' : UserId,
}
export interface UserProfileInput {
  'fullName' : string,
  'languageInterests' : Array<string>,
  'heritageRegion' : string,
  'email' : string,
}
export interface UserTraditionPrefs {
  'heritageLanguages' : Array<string>,
  'savedItemIds' : Array<ItemId>,
  'userId' : UserId,
  'heritageRegions' : Array<string>,
  'updatedAt' : Timestamp,
}
export interface _SERVICE {
  'addCourse' : ActorMethod<
    [
      string,
      string,
      CourseCategory,
      string,
      bigint,
      bigint,
      boolean,
      [] | [Timestamp],
      bigint,
      string,
    ],
    Course
  >,
  'addFamilyMember' : ActorMethod<[ItemId, string], boolean>,
  'addFestival' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      Array<string>,
      string,
    ],
    Festival
  >,
  'addLesson' : ActorMethod<
    [string, string, string, string, Array<string>],
    DailyLesson
  >,
  'addListing' : ActorMethod<
    [string, string, bigint, ProductCategory, Array<string>, bigint, string],
    Listing
  >,
  'addStoryItem' : ActorMethod<
    [
      string,
      string,
      MediaType,
      string,
      Array<string>,
      Array<string>,
      [] | [bigint],
      string,
    ],
    StoryItem
  >,
  'addTradition' : ActorMethod<
    [
      string,
      string,
      TraditionCategory,
      string,
      Array<string>,
      string,
      Array<string>,
      Array<string>,
    ],
    TraditionItem
  >,
  'bookMentor' : ActorMethod<
    [UserId, Timestamp, bigint, string],
    MentorBooking
  >,
  'cancelMentorBooking' : ActorMethod<[ItemId], boolean>,
  'completeCourse' : ActorMethod<[ItemId], [] | [Enrollment]>,
  'completeLesson' : ActorMethod<[ItemId, bigint], [] | [LanguageProgress]>,
  'createFestivalPlan' : ActorMethod<
    [ItemId, [] | [Timestamp], Array<string>, string],
    FestivalPlan
  >,
  'createOrder' : ActorMethod<
    [ItemId, UserId, bigint, bigint, string, string],
    Order
  >,
  'deleteARCapture' : ActorMethod<[string], boolean>,
  'deleteFestivalPlan' : ActorMethod<[ItemId], boolean>,
  'deleteHeritageProfile' : ActorMethod<[], boolean>,
  'deleteListing' : ActorMethod<[ItemId], boolean>,
  'deleteStoryItem' : ActorMethod<[ItemId], boolean>,
  'enrollInCourse' : ActorMethod<[ItemId], Enrollment>,
  'filterFestivalsByRegion' : ActorMethod<[string], Array<Festival>>,
  'filterTraditionsByRegion' : ActorMethod<[string], Array<TraditionItem>>,
  'filterTraditionsByType' : ActorMethod<[string], Array<TraditionItem>>,
  'generateAncestryInsights' : ActorMethod<
    [string, string, string, string, string],
    AncestryInsights
  >,
  'generateNarrative' : ActorMethod<[ItemId], [] | [string]>,
  'getARCaptures' : ActorMethod<[], Array<ARCapture>>,
  'getCourse' : ActorMethod<[ItemId], [] | [Course]>,
  'getFestival' : ActorMethod<[ItemId], [] | [Festival]>,
  'getHeritageProfile' : ActorMethod<[], [] | [HeritageProfile]>,
  'getLanguageProgress' : ActorMethod<[], [] | [LanguageProgress]>,
  'getLesson' : ActorMethod<[ItemId], [] | [DailyLesson]>,
  'getLessonsByLanguage' : ActorMethod<[string], Array<DailyLesson>>,
  'getListing' : ActorMethod<[ItemId], [] | [Listing]>,
  'getMyBuyerOrders' : ActorMethod<[], Array<Order>>,
  'getMyEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getMyFamilyTimeline' : ActorMethod<[], [] | [FamilyTimeline]>,
  'getMyFestivalPlans' : ActorMethod<[], Array<FestivalPlan>>,
  'getMyListings' : ActorMethod<[], Array<Listing>>,
  'getMyMentorBookings' : ActorMethod<[], Array<MentorBooking>>,
  'getMySellerOrders' : ActorMethod<[], Array<Order>>,
  'getMySellerStats' : ActorMethod<[], SellerStats>,
  'getMyStoryItems' : ActorMethod<[], Array<StoryItem>>,
  'getMyTraditionPrefs' : ActorMethod<[], [] | [UserTraditionPrefs]>,
  'getPersonalizedFestivals' : ActorMethod<
    [Array<string>, Array<string>],
    Array<Festival>
  >,
  'getRecommendedTraditions' : ActorMethod<[], Array<TraditionItem>>,
  'getStoryItem' : ActorMethod<[ItemId], [] | [StoryItem]>,
  'getTradition' : ActorMethod<[ItemId], [] | [TraditionItem]>,
  'getUserActivitySummary' : ActorMethod<
    [],
    { 'ok' : UserActivitySummary } |
      { 'err' : string }
  >,
  'getUserProfile' : ActorMethod<
    [],
    { 'ok' : UserProfile } |
      { 'err' : string }
  >,
  'listActiveListings' : ActorMethod<[], Array<Listing>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listCoursesByCategory' : ActorMethod<[string], Array<Course>>,
  'listFestivals' : ActorMethod<[], Array<Festival>>,
  'listTraditions' : ActorMethod<[], Array<TraditionItem>>,
  'listingsByCategory' : ActorMethod<[string], Array<Listing>>,
  'removeFamilyMember' : ActorMethod<[ItemId, string], boolean>,
  'saveARCapture' : ActorMethod<[string, string, string], ARCapture>,
  'saveHeritageProfile' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    HeritageProfile
  >,
  'saveTraditionItem' : ActorMethod<[ItemId], boolean>,
  'saveUserProfile' : ActorMethod<
    [UserProfileInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setTraditionPrefs' : ActorMethod<
    [Array<string>, Array<string>],
    UserTraditionPrefs
  >,
  'startLanguage' : ActorMethod<[string], LanguageProgress>,
  'unsaveTraditionItem' : ActorMethod<[ItemId], boolean>,
  'updateCourseProgress' : ActorMethod<[ItemId, bigint], [] | [Enrollment]>,
  'updateFestivalPlan' : ActorMethod<
    [ItemId, [] | [Timestamp], Array<string>, string],
    [] | [FestivalPlan]
  >,
  'updateLanguageProgress' : ActorMethod<
    [bigint, bigint, bigint, bigint, string, Array<string>],
    [] | [LanguageProgress]
  >,
  'updateLastLogin' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'updateListing' : ActorMethod<
    [ItemId, string, string, bigint, bigint, boolean],
    [] | [Listing]
  >,
  'updateOrderStatus' : ActorMethod<[ItemId, OrderStatus], [] | [Order]>,
  'updateStoryItem' : ActorMethod<
    [ItemId, string, string, Array<string>, string],
    [] | [StoryItem]
  >,
  'upsertFamilyTimeline' : ActorMethod<
    [string, string, Array<ItemId>],
    FamilyTimeline
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];