/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ARCapture {
    id: string;
    title: string;
    imageData: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    sceneId: string;
}
export interface MentorBooking {
    id: ItemId;
    status: string;
    userId: UserId;
    createdAt: Timestamp;
    instructorId: UserId;
    durationMinutes: bigint;
    notes: string;
    scheduledAt: Timestamp;
}
export type Timestamp = bigint;
export interface HeritageProfile {
    region: string;
    foods: Array<string>;
    familyBackground: string;
    userId: UserId;
    createdAt: Timestamp;
    migrationStory: string;
    surname: string;
    festivals: Array<string>;
    ancestryInsights: string;
    language: string;
    updatedAt: Timestamp;
    grandparentsOrigin: string;
    traditionalOccupations: Array<string>;
    forgottenCustoms: Array<string>;
}
export interface Enrollment {
    id: ItemId;
    completedAt?: Timestamp;
    userId: UserId;
    enrolledAt: Timestamp;
    certified: boolean;
    courseId: ItemId;
    progressPct: bigint;
}
export interface UserActivitySummary {
    storiesSaved: bigint;
    arCaptures: bigint;
    languageLessons: bigint;
    coursesEnrolled: bigint;
    ordersPlaced: bigint;
    festivalPlans: bigint;
    heritageScans: bigint;
}
export interface Course {
    id: ItemId;
    title: string;
    createdAt: Timestamp;
    description: string;
    isLive: boolean;
    instructorId: UserId;
    imageUrl: string;
    durationMinutes: bigint;
    category: CourseCategory;
    maxParticipants: bigint;
    price: bigint;
    instructorName: string;
    scheduledAt?: Timestamp;
}
export interface StoryItem {
    id: ItemId;
    title: string;
    yearApprox?: bigint;
    userId: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    peopleTagged: Array<string>;
    updatedAt: Timestamp;
    fileId: string;
    narration: string;
    mediaType: MediaType;
}
export type ItemId = bigint;
export interface LanguageProgress {
    wordsLearned: bigint;
    startedAt: Timestamp;
    userId: UserId;
    lastActiveAt: Timestamp;
    totalLessonsCompleted: bigint;
    conversationLevel: string;
    streakDays: bigint;
    currentLesson: bigint;
    scriptsLearned: Array<string>;
    languageChosen: string;
    pronunciationScore: bigint;
}
export interface UserTraditionPrefs {
    heritageLanguages: Array<string>;
    savedItemIds: Array<ItemId>;
    userId: UserId;
    heritageRegions: Array<string>;
    updatedAt: Timestamp;
}
export interface TraditionItem {
    id: ItemId;
    region: string;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    languages: Array<string>;
    description: string;
    steps: Array<string>;
    imageUrl: string;
    category: TraditionCategory;
}
export interface FestivalPlan {
    id: ItemId;
    reminderAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    festivalId: ItemId;
    notes: string;
    familyParticipants: Array<string>;
}
export interface SellerStats {
    totalOrders: bigint;
    totalListings: bigint;
    sellerId: UserId;
    rating: bigint;
    totalRevenue: bigint;
}
export interface Listing {
    id: ItemId;
    region: string;
    title: string;
    imageUrls: Array<string>;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    category: ProductCategory;
    sellerId: UserId;
    price: bigint;
}
export interface FamilyTreeNode {
    era: string;
    region: string;
    relation: string;
    name: string;
}
export interface Festival {
    id: ItemId;
    region: string;
    celebrationGuide: string;
    recipes: Array<string>;
    meaning: string;
    date: string;
    name: string;
    createdAt: Timestamp;
    languages: Array<string>;
    description: string;
    imageUrl: string;
    clothingSuggestions: Array<string>;
    rituals: Array<string>;
}
export interface FamilyTimeline {
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    itemIds: Array<ItemId>;
}
export interface Order {
    id: ItemId;
    status: OrderStatus;
    listingId: ItemId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    buyerId: UserId;
    quantity: bigint;
    shippingAddress: string;
    sellerId: UserId;
    stripeSessionId: string;
    totalPrice: bigint;
}
export interface AncestryInsights {
    foods: Array<string>;
    migrationStory: string;
    festivals: Array<string>;
    familyTreeNodes: Array<FamilyTreeNode>;
    traditionalOccupations: Array<string>;
    forgottenCustoms: Array<string>;
}
export type UserId = Principal;
export interface UserProfileInput {
    fullName: string;
    languageInterests: Array<string>;
    heritageRegion: string;
    email: string;
}
export interface UserProfile {
    lastLoginAt: Timestamp;
    createdAt: Timestamp;
    fullName: string;
    languageInterests: Array<string>;
    heritageRegion: string;
    email: string;
    principalId: UserId;
}
export interface DailyLesson {
    id: ItemId;
    title: string;
    content: string;
    lessonNumber: bigint;
    createdAt: Timestamp;
    audioUrl: string;
    language: string;
    practiceWords: Array<string>;
}
export enum CourseCategory {
    music = "music",
    yoga = "yoga",
    cooking = "cooking",
    pottery = "pottery",
    martialArts = "martialArts",
    regionalArts = "regionalArts",
    dance = "dance",
    weaving = "weaving",
    calligraphy = "calligraphy"
}
export enum MediaType {
    voiceNote = "voiceNote",
    video = "video",
    letter = "letter",
    handwrittenNote = "handwrittenNote",
    photo = "photo"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid",
    delivered = "delivered"
}
export enum ProductCategory {
    art = "art",
    artisanProduct = "artisanProduct",
    book = "book",
    instrument = "instrument",
    craft = "craft",
    jewelry = "jewelry",
    textile = "textile"
}
export enum TraditionCategory {
    clothing = "clothing",
    custom = "custom",
    ritual = "ritual",
    spiritualPractice = "spiritualPractice",
    folkSong = "folkSong",
    dance = "dance",
    celebration = "celebration",
    recipe = "recipe"
}
export interface backendInterface {
    addCourse(title: string, description: string, category: CourseCategory, instructorName: string, price: bigint, durationMinutes: bigint, isLive: boolean, scheduledAt: Timestamp | null, maxParticipants: bigint, imageUrl: string): Promise<Course>;
    addFamilyMember(planId: ItemId, member: string): Promise<boolean>;
    addFestival(name: string, description: string, meaning: string, rituals: Array<string>, celebrationGuide: string, recipes: Array<string>, clothingSuggestions: Array<string>, date: string, region: string, languages: Array<string>, imageUrl: string): Promise<Festival>;
    addLesson(language: string, title: string, content: string, audioUrl: string, practiceWords: Array<string>): Promise<DailyLesson>;
    addListing(title: string, description: string, price: bigint, category: ProductCategory, imageUrls: Array<string>, stock: bigint, region: string): Promise<Listing>;
    addStoryItem(title: string, description: string, mediaType: MediaType, fileId: string, tags: Array<string>, peopleTagged: Array<string>, yearApprox: bigint | null, narration: string): Promise<StoryItem>;
    addTradition(title: string, description: string, category: TraditionCategory, region: string, languages: Array<string>, imageUrl: string, steps: Array<string>, tags: Array<string>): Promise<TraditionItem>;
    bookMentor(instructorId: UserId, scheduledAt: Timestamp, durationMinutes: bigint, notes: string): Promise<MentorBooking>;
    cancelMentorBooking(bookingId: ItemId): Promise<boolean>;
    completeCourse(enrollmentId: ItemId): Promise<Enrollment | null>;
    completeLesson(lessonId: ItemId, score: bigint): Promise<LanguageProgress | null>;
    createFestivalPlan(festivalId: ItemId, reminderAt: Timestamp | null, familyParticipants: Array<string>, notes: string): Promise<FestivalPlan>;
    createOrder(listingId: ItemId, sellerId: UserId, quantity: bigint, totalPrice: bigint, stripeSessionId: string, shippingAddress: string): Promise<Order>;
    deleteARCapture(id: string): Promise<boolean>;
    deleteFestivalPlan(planId: ItemId): Promise<boolean>;
    deleteHeritageProfile(): Promise<boolean>;
    deleteListing(id: ItemId): Promise<boolean>;
    deleteStoryItem(id: ItemId): Promise<boolean>;
    enrollInCourse(courseId: ItemId): Promise<Enrollment>;
    filterFestivalsByRegion(region: string): Promise<Array<Festival>>;
    filterTraditionsByRegion(region: string): Promise<Array<TraditionItem>>;
    filterTraditionsByType(traditionType: string): Promise<Array<TraditionItem>>;
    generateAncestryInsights(surname: string, region: string, language: string, familyBackground: string, grandparentsOrigin: string): Promise<AncestryInsights>;
    generateNarrative(itemId: ItemId): Promise<string | null>;
    getARCaptures(): Promise<Array<ARCapture>>;
    getCourse(id: ItemId): Promise<Course | null>;
    getFestival(id: ItemId): Promise<Festival | null>;
    getHeritageProfile(): Promise<HeritageProfile | null>;
    getLanguageProgress(): Promise<LanguageProgress | null>;
    getLesson(id: ItemId): Promise<DailyLesson | null>;
    getLessonsByLanguage(language: string): Promise<Array<DailyLesson>>;
    getListing(id: ItemId): Promise<Listing | null>;
    getMyBuyerOrders(): Promise<Array<Order>>;
    getMyEnrollments(): Promise<Array<Enrollment>>;
    getMyFamilyTimeline(): Promise<FamilyTimeline | null>;
    getMyFestivalPlans(): Promise<Array<FestivalPlan>>;
    getMyListings(): Promise<Array<Listing>>;
    getMyMentorBookings(): Promise<Array<MentorBooking>>;
    getMySellerOrders(): Promise<Array<Order>>;
    getMySellerStats(): Promise<SellerStats>;
    getMyStoryItems(): Promise<Array<StoryItem>>;
    getMyTraditionPrefs(): Promise<UserTraditionPrefs | null>;
    getPersonalizedFestivals(regions: Array<string>, languages: Array<string>): Promise<Array<Festival>>;
    getRecommendedTraditions(): Promise<Array<TraditionItem>>;
    getStoryItem(id: ItemId): Promise<StoryItem | null>;
    getTradition(id: ItemId): Promise<TraditionItem | null>;
    getUserActivitySummary(): Promise<{
        __kind__: "ok";
        ok: UserActivitySummary;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getUserProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }>;
    listActiveListings(): Promise<Array<Listing>>;
    listCourses(): Promise<Array<Course>>;
    listCoursesByCategory(category: string): Promise<Array<Course>>;
    listFestivals(): Promise<Array<Festival>>;
    listTraditions(): Promise<Array<TraditionItem>>;
    listingsByCategory(category: string): Promise<Array<Listing>>;
    removeFamilyMember(planId: ItemId, member: string): Promise<boolean>;
    saveARCapture(sceneId: string, imageData: string, title: string): Promise<ARCapture>;
    saveHeritageProfile(surname: string, region: string, language: string, familyBackground: string, grandparentsOrigin: string, ancestryInsights: string, migrationStory: string, forgottenCustoms: Array<string>, traditionalOccupations: Array<string>, festivals: Array<string>, foods: Array<string>): Promise<HeritageProfile>;
    saveTraditionItem(itemId: ItemId): Promise<boolean>;
    saveUserProfile(input: UserProfileInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setTraditionPrefs(heritageRegions: Array<string>, heritageLanguages: Array<string>): Promise<UserTraditionPrefs>;
    startLanguage(languageChosen: string): Promise<LanguageProgress>;
    unsaveTraditionItem(itemId: ItemId): Promise<boolean>;
    updateCourseProgress(enrollmentId: ItemId, progressPct: bigint): Promise<Enrollment | null>;
    updateFestivalPlan(planId: ItemId, reminderAt: Timestamp | null, familyParticipants: Array<string>, notes: string): Promise<FestivalPlan | null>;
    updateLanguageProgress(currentLesson: bigint, streakDays: bigint, wordsLearned: bigint, pronunciationScore: bigint, conversationLevel: string, scriptsLearned: Array<string>): Promise<LanguageProgress | null>;
    updateLastLogin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateListing(id: ItemId, title: string, description: string, price: bigint, stock: bigint, isActive: boolean): Promise<Listing | null>;
    updateOrderStatus(orderId: ItemId, status: OrderStatus): Promise<Order | null>;
    updateStoryItem(id: ItemId, title: string, description: string, tags: Array<string>, narration: string): Promise<StoryItem | null>;
    upsertFamilyTimeline(title: string, description: string, itemIds: Array<ItemId>): Promise<FamilyTimeline>;
}
import type { Course as _Course, CourseCategory as _CourseCategory, DailyLesson as _DailyLesson, Enrollment as _Enrollment, FamilyTimeline as _FamilyTimeline, Festival as _Festival, FestivalPlan as _FestivalPlan, HeritageProfile as _HeritageProfile, ItemId as _ItemId, LanguageProgress as _LanguageProgress, Listing as _Listing, MediaType as _MediaType, Order as _Order, OrderStatus as _OrderStatus, ProductCategory as _ProductCategory, StoryItem as _StoryItem, Timestamp as _Timestamp, TraditionCategory as _TraditionCategory, TraditionItem as _TraditionItem, UserActivitySummary as _UserActivitySummary, UserId as _UserId, UserProfile as _UserProfile, UserTraditionPrefs as _UserTraditionPrefs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCourse(arg0: string, arg1: string, arg2: CourseCategory, arg3: string, arg4: bigint, arg5: bigint, arg6: boolean, arg7: Timestamp | null, arg8: bigint, arg9: string): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, to_candid_CourseCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
                return from_candid_Course_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, to_candid_CourseCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9);
            return from_candid_Course_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFamilyMember(arg0: ItemId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addFamilyMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFamilyMember(arg0, arg1);
            return result;
        }
    }
    async addFestival(arg0: string, arg1: string, arg2: string, arg3: Array<string>, arg4: string, arg5: Array<string>, arg6: Array<string>, arg7: string, arg8: string, arg9: Array<string>, arg10: string): Promise<Festival> {
        if (this.processError) {
            try {
                const result = await this.actor.addFestival(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFestival(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async addLesson(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<DailyLesson> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addListing(arg0: string, arg1: string, arg2: bigint, arg3: ProductCategory, arg4: Array<string>, arg5: bigint, arg6: string): Promise<Listing> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(arg0, arg1, arg2, to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return from_candid_Listing_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(arg0, arg1, arg2, to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return from_candid_Listing_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStoryItem(arg0: string, arg1: string, arg2: MediaType, arg3: string, arg4: Array<string>, arg5: Array<string>, arg6: bigint | null, arg7: string): Promise<StoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoryItem(arg0, arg1, to_candid_MediaType_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_StoryItem_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoryItem(arg0, arg1, to_candid_MediaType_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_StoryItem_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTradition(arg0: string, arg1: string, arg2: TraditionCategory, arg3: string, arg4: Array<string>, arg5: string, arg6: Array<string>, arg7: Array<string>): Promise<TraditionItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradition(arg0, arg1, to_candid_TraditionCategory_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return from_candid_TraditionItem_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradition(arg0, arg1, to_candid_TraditionCategory_n23(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return from_candid_TraditionItem_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async bookMentor(arg0: UserId, arg1: Timestamp, arg2: bigint, arg3: string): Promise<MentorBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.bookMentor(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookMentor(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async cancelMentorBooking(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelMentorBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelMentorBooking(arg0);
            return result;
        }
    }
    async completeCourse(arg0: ItemId): Promise<Enrollment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeCourse(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeCourse(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeLesson(arg0: ItemId, arg1: bigint): Promise<LanguageProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0, arg1);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0, arg1);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFestivalPlan(arg0: ItemId, arg1: Timestamp | null, arg2: Array<string>, arg3: string): Promise<FestivalPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.createFestivalPlan(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_FestivalPlan_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFestivalPlan(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_FestivalPlan_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: ItemId, arg1: UserId, arg2: bigint, arg3: bigint, arg4: string, arg5: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Order_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Order_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteARCapture(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteARCapture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteARCapture(arg0);
            return result;
        }
    }
    async deleteFestivalPlan(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFestivalPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFestivalPlan(arg0);
            return result;
        }
    }
    async deleteHeritageProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHeritageProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHeritageProfile();
            return result;
        }
    }
    async deleteListing(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteStoryItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStoryItem(arg0);
            return result;
        }
    }
    async enrollInCourse(arg0: ItemId): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterFestivalsByRegion(arg0: string): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterFestivalsByRegion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterFestivalsByRegion(arg0);
            return result;
        }
    }
    async filterTraditionsByRegion(arg0: string): Promise<Array<TraditionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTraditionsByRegion(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTraditionsByRegion(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterTraditionsByType(arg0: string): Promise<Array<TraditionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTraditionsByType(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTraditionsByType(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateAncestryInsights(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<AncestryInsights> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAncestryInsights(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAncestryInsights(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async generateNarrative(arg0: ItemId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.generateNarrative(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateNarrative(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getARCaptures(): Promise<Array<ARCapture>> {
        if (this.processError) {
            try {
                const result = await this.actor.getARCaptures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getARCaptures();
            return result;
        }
    }
    async getCourse(arg0: ItemId): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFestival(arg0: ItemId): Promise<Festival | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestival(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestival(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeritageProfile(): Promise<HeritageProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeritageProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeritageProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLanguageProgress(): Promise<LanguageProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLanguageProgress();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLanguageProgress();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: ItemId): Promise<DailyLesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonsByLanguage(arg0: string): Promise<Array<DailyLesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonsByLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonsByLanguage(arg0);
            return result;
        }
    }
    async getListing(arg0: ItemId): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBuyerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBuyerOrders();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBuyerOrders();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEnrollments(): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFamilyTimeline(): Promise<FamilyTimeline | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFamilyTimeline();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFamilyTimeline();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyFestivalPlans(): Promise<Array<FestivalPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFestivalPlans();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFestivalPlans();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMentorBookings(): Promise<Array<MentorBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMentorBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMentorBookings();
            return result;
        }
    }
    async getMySellerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerOrders();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerOrders();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySellerStats(): Promise<SellerStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerStats();
            return result;
        }
    }
    async getMyStoryItems(): Promise<Array<StoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStoryItems();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStoryItems();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTraditionPrefs(): Promise<UserTraditionPrefs | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTraditionPrefs();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTraditionPrefs();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalizedFestivals(arg0: Array<string>, arg1: Array<string>): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedFestivals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedFestivals(arg0, arg1);
            return result;
        }
    }
    async getRecommendedTraditions(): Promise<Array<TraditionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedTraditions();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedTraditions();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoryItem(arg0: ItemId): Promise<StoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryItem(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryItem(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradition(arg0: ItemId): Promise<TraditionItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradition(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradition(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserActivitySummary(): Promise<{
        __kind__: "ok";
        ok: UserActivitySummary;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivitySummary();
                return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivitySummary();
            return from_candid_variant_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_variant_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_variant_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveListings();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveListings();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCoursesByCategory(arg0: string): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCoursesByCategory(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCoursesByCategory(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFestivals(): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFestivals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFestivals();
            return result;
        }
    }
    async listTraditions(): Promise<Array<TraditionItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTraditions();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTraditions();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listingsByCategory(arg0: string): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.listingsByCategory(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listingsByCategory(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFamilyMember(arg0: ItemId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFamilyMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFamilyMember(arg0, arg1);
            return result;
        }
    }
    async saveARCapture(arg0: string, arg1: string, arg2: string): Promise<ARCapture> {
        if (this.processError) {
            try {
                const result = await this.actor.saveARCapture(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveARCapture(arg0, arg1, arg2);
            return result;
        }
    }
    async saveHeritageProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: Array<string>, arg8: Array<string>, arg9: Array<string>, arg10: Array<string>): Promise<HeritageProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHeritageProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHeritageProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async saveTraditionItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTraditionItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTraditionItem(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfileInput): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0);
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0);
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTraditionPrefs(arg0: Array<string>, arg1: Array<string>): Promise<UserTraditionPrefs> {
        if (this.processError) {
            try {
                const result = await this.actor.setTraditionPrefs(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTraditionPrefs(arg0, arg1);
            return result;
        }
    }
    async startLanguage(arg0: string): Promise<LanguageProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.startLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startLanguage(arg0);
            return result;
        }
    }
    async unsaveTraditionItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveTraditionItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveTraditionItem(arg0);
            return result;
        }
    }
    async updateCourseProgress(arg0: ItemId, arg1: bigint): Promise<Enrollment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourseProgress(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourseProgress(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFestivalPlan(arg0: ItemId, arg1: Timestamp | null, arg2: Array<string>, arg3: string): Promise<FestivalPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFestivalPlan(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFestivalPlan(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLanguageProgress(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string, arg5: Array<string>): Promise<LanguageProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLanguageProgress(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLanguageProgress(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLastLogin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastLogin();
                return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastLogin();
            return from_candid_variant_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListing(arg0: ItemId, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: boolean): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: ItemId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n60(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n60(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStoryItem(arg0: ItemId, arg1: string, arg2: string, arg3: Array<string>, arg4: string): Promise<StoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoryItem(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoryItem(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertFamilyTimeline(arg0: string, arg1: string, arg2: Array<ItemId>): Promise<FamilyTimeline> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertFamilyTimeline(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertFamilyTimeline(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_CourseCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CourseCategory): CourseCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Enrollment_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enrollment): Enrollment {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_FestivalPlan_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FestivalPlan): FestivalPlan {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Listing_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_StoryItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryItem): StoryItem {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TraditionCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TraditionCategory): TraditionCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TraditionItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TraditionItem): TraditionItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Enrollment]): Enrollment | null {
    return value.length === 0 ? null : from_candid_Enrollment_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LanguageProgress]): LanguageProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Festival]): Festival | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeritageProfile]): HeritageProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyLesson]): DailyLesson | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FamilyTimeline]): FamilyTimeline | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserTraditionPrefs]): UserTraditionPrefs | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoryItem]): StoryItem | null {
    return value.length === 0 ? null : from_candid_StoryItem_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TraditionItem]): TraditionItem | null {
    return value.length === 0 ? null : from_candid_TraditionItem_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FestivalPlan]): FestivalPlan | null {
    return value.length === 0 ? null : from_candid_FestivalPlan_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    region: string;
    title: string;
    imageUrls: Array<string>;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    stock: bigint;
    category: _ProductCategory;
    sellerId: _UserId;
    price: bigint;
}): {
    id: ItemId;
    region: string;
    title: string;
    imageUrls: Array<string>;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    category: ProductCategory;
    sellerId: UserId;
    price: bigint;
} {
    return {
        id: value.id,
        region: value.region,
        title: value.title,
        imageUrls: value.imageUrls,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        stock: value.stock,
        category: from_candid_ProductCategory_n13(_uploadFile, _downloadFile, value.category),
        sellerId: value.sellerId,
        price: value.price
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    title: string;
    yearApprox: [] | [bigint];
    userId: _UserId;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    peopleTagged: Array<string>;
    updatedAt: _Timestamp;
    fileId: string;
    narration: string;
    mediaType: _MediaType;
}): {
    id: ItemId;
    title: string;
    yearApprox?: bigint;
    userId: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    peopleTagged: Array<string>;
    updatedAt: Timestamp;
    fileId: string;
    narration: string;
    mediaType: MediaType;
} {
    return {
        id: value.id,
        title: value.title,
        yearApprox: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.yearApprox)),
        userId: value.userId,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        peopleTagged: value.peopleTagged,
        updatedAt: value.updatedAt,
        fileId: value.fileId,
        narration: value.narration,
        mediaType: from_candid_MediaType_n21(_uploadFile, _downloadFile, value.mediaType)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    region: string;
    title: string;
    createdAt: _Timestamp;
    tags: Array<string>;
    languages: Array<string>;
    description: string;
    steps: Array<string>;
    imageUrl: string;
    category: _TraditionCategory;
}): {
    id: ItemId;
    region: string;
    title: string;
    createdAt: Timestamp;
    tags: Array<string>;
    languages: Array<string>;
    description: string;
    steps: Array<string>;
    imageUrl: string;
    category: TraditionCategory;
} {
    return {
        id: value.id,
        region: value.region,
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        languages: value.languages,
        description: value.description,
        steps: value.steps,
        imageUrl: value.imageUrl,
        category: from_candid_TraditionCategory_n27(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    completedAt: [] | [_Timestamp];
    userId: _UserId;
    enrolledAt: _Timestamp;
    certified: boolean;
    courseId: _ItemId;
    progressPct: bigint;
}): {
    id: ItemId;
    completedAt?: Timestamp;
    userId: UserId;
    enrolledAt: Timestamp;
    certified: boolean;
    courseId: ItemId;
    progressPct: bigint;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.completedAt)),
        userId: value.userId,
        enrolledAt: value.enrolledAt,
        certified: value.certified,
        courseId: value.courseId,
        progressPct: value.progressPct
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    reminderAt: [] | [_Timestamp];
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    festivalId: _ItemId;
    notes: string;
    familyParticipants: Array<string>;
}): {
    id: ItemId;
    reminderAt?: Timestamp;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    festivalId: ItemId;
    notes: string;
    familyParticipants: Array<string>;
} {
    return {
        id: value.id,
        reminderAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.reminderAt)),
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        festivalId: value.festivalId,
        notes: value.notes,
        familyParticipants: value.familyParticipants
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    status: _OrderStatus;
    listingId: _ItemId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    buyerId: _UserId;
    quantity: bigint;
    shippingAddress: string;
    sellerId: _UserId;
    stripeSessionId: string;
    totalPrice: bigint;
}): {
    id: ItemId;
    status: OrderStatus;
    listingId: ItemId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    buyerId: UserId;
    quantity: bigint;
    shippingAddress: string;
    sellerId: UserId;
    stripeSessionId: string;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n37(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        buyerId: value.buyerId,
        quantity: value.quantity,
        shippingAddress: value.shippingAddress,
        sellerId: value.sellerId,
        stripeSessionId: value.stripeSessionId,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    title: string;
    createdAt: _Timestamp;
    description: string;
    isLive: boolean;
    instructorId: _UserId;
    imageUrl: string;
    durationMinutes: bigint;
    category: _CourseCategory;
    maxParticipants: bigint;
    price: bigint;
    instructorName: string;
    scheduledAt: [] | [_Timestamp];
}): {
    id: ItemId;
    title: string;
    createdAt: Timestamp;
    description: string;
    isLive: boolean;
    instructorId: UserId;
    imageUrl: string;
    durationMinutes: bigint;
    category: CourseCategory;
    maxParticipants: bigint;
    price: bigint;
    instructorName: string;
    scheduledAt?: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        isLive: value.isLive,
        instructorId: value.instructorId,
        imageUrl: value.imageUrl,
        durationMinutes: value.durationMinutes,
        category: from_candid_CourseCategory_n6(_uploadFile, _downloadFile, value.category),
        maxParticipants: value.maxParticipants,
        price: value.price,
        instructorName: value.instructorName,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    art: null;
} | {
    artisanProduct: null;
} | {
    book: null;
} | {
    instrument: null;
} | {
    craft: null;
} | {
    jewelry: null;
} | {
    textile: null;
}): ProductCategory {
    return "art" in value ? ProductCategory.art : "artisanProduct" in value ? ProductCategory.artisanProduct : "book" in value ? ProductCategory.book : "instrument" in value ? ProductCategory.instrument : "craft" in value ? ProductCategory.craft : "jewelry" in value ? ProductCategory.jewelry : "textile" in value ? ProductCategory.textile : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voiceNote: null;
} | {
    video: null;
} | {
    letter: null;
} | {
    handwrittenNote: null;
} | {
    photo: null;
}): MediaType {
    return "voiceNote" in value ? MediaType.voiceNote : "video" in value ? MediaType.video : "letter" in value ? MediaType.letter : "handwrittenNote" in value ? MediaType.handwrittenNote : "photo" in value ? MediaType.photo : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    custom: null;
} | {
    ritual: null;
} | {
    spiritualPractice: null;
} | {
    folkSong: null;
} | {
    dance: null;
} | {
    celebration: null;
} | {
    recipe: null;
}): TraditionCategory {
    return "clothing" in value ? TraditionCategory.clothing : "custom" in value ? TraditionCategory.custom : "ritual" in value ? TraditionCategory.ritual : "spiritualPractice" in value ? TraditionCategory.spiritualPractice : "folkSong" in value ? TraditionCategory.folkSong : "dance" in value ? TraditionCategory.dance : "celebration" in value ? TraditionCategory.celebration : "recipe" in value ? TraditionCategory.recipe : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserActivitySummary;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserActivitySummary;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    music: null;
} | {
    yoga: null;
} | {
    cooking: null;
} | {
    pottery: null;
} | {
    martialArts: null;
} | {
    regionalArts: null;
} | {
    dance: null;
} | {
    weaving: null;
} | {
    calligraphy: null;
}): CourseCategory {
    return "music" in value ? CourseCategory.music : "yoga" in value ? CourseCategory.yoga : "cooking" in value ? CourseCategory.cooking : "pottery" in value ? CourseCategory.pottery : "martialArts" in value ? CourseCategory.martialArts : "regionalArts" in value ? CourseCategory.regionalArts : "dance" in value ? CourseCategory.dance : "weaving" in value ? CourseCategory.weaving : "calligraphy" in value ? CourseCategory.calligraphy : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TraditionItem>): Array<TraditionItem> {
    return value.map((x)=>from_candid_TraditionItem_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enrollment>): Array<Enrollment> {
    return value.map((x)=>from_candid_Enrollment_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FestivalPlan>): Array<FestivalPlan> {
    return value.map((x)=>from_candid_FestivalPlan_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryItem>): Array<StoryItem> {
    return value.map((x)=>from_candid_StoryItem_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CourseCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseCategory): _CourseCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TraditionCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TraditionCategory): _TraditionCategory {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    art: null;
} | {
    artisanProduct: null;
} | {
    book: null;
} | {
    instrument: null;
} | {
    craft: null;
} | {
    jewelry: null;
} | {
    textile: null;
} {
    return value == ProductCategory.art ? {
        art: null
    } : value == ProductCategory.artisanProduct ? {
        artisanProduct: null
    } : value == ProductCategory.book ? {
        book: null
    } : value == ProductCategory.instrument ? {
        instrument: null
    } : value == ProductCategory.craft ? {
        craft: null
    } : value == ProductCategory.jewelry ? {
        jewelry: null
    } : value == ProductCategory.textile ? {
        textile: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    voiceNote: null;
} | {
    video: null;
} | {
    letter: null;
} | {
    handwrittenNote: null;
} | {
    photo: null;
} {
    return value == MediaType.voiceNote ? {
        voiceNote: null
    } : value == MediaType.video ? {
        video: null
    } : value == MediaType.letter ? {
        letter: null
    } : value == MediaType.handwrittenNote ? {
        handwrittenNote: null
    } : value == MediaType.photo ? {
        photo: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseCategory): {
    music: null;
} | {
    yoga: null;
} | {
    cooking: null;
} | {
    pottery: null;
} | {
    martialArts: null;
} | {
    regionalArts: null;
} | {
    dance: null;
} | {
    weaving: null;
} | {
    calligraphy: null;
} {
    return value == CourseCategory.music ? {
        music: null
    } : value == CourseCategory.yoga ? {
        yoga: null
    } : value == CourseCategory.cooking ? {
        cooking: null
    } : value == CourseCategory.pottery ? {
        pottery: null
    } : value == CourseCategory.martialArts ? {
        martialArts: null
    } : value == CourseCategory.regionalArts ? {
        regionalArts: null
    } : value == CourseCategory.dance ? {
        dance: null
    } : value == CourseCategory.weaving ? {
        weaving: null
    } : value == CourseCategory.calligraphy ? {
        calligraphy: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TraditionCategory): {
    clothing: null;
} | {
    custom: null;
} | {
    ritual: null;
} | {
    spiritualPractice: null;
} | {
    folkSong: null;
} | {
    dance: null;
} | {
    celebration: null;
} | {
    recipe: null;
} {
    return value == TraditionCategory.clothing ? {
        clothing: null
    } : value == TraditionCategory.custom ? {
        custom: null
    } : value == TraditionCategory.ritual ? {
        ritual: null
    } : value == TraditionCategory.spiritualPractice ? {
        spiritualPractice: null
    } : value == TraditionCategory.folkSong ? {
        folkSong: null
    } : value == TraditionCategory.dance ? {
        dance: null
    } : value == TraditionCategory.celebration ? {
        celebration: null
    } : value == TraditionCategory.recipe ? {
        recipe: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
